version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
